/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AutoSell.Manutencoes;

/**
 *
 * @author David
 */

import main.java.AutoSell.Veiculos.*;
import AutoSell.DadosAplicacao;
import main.java.AutoSell.Manutencoes.*;
import AutoSell.Manutencoes.RegistarManutencao;






public class Menu_Manutencoes extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Clientes
     */
    public Menu_Manutencoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltarMenu = new javax.swing.JButton();
        btnRegistarVeiculos = new javax.swing.JButton();
        btnRegistarVeiculos2 = new javax.swing.JButton();
        btnRegistarVeiculos3 = new javax.swing.JButton();

        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestão de Manutenções");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        btnVoltarMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnVoltarMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVoltarMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarMenu.setText("Voltar ao Menu Principal");
        btnVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenuActionPerformed(evt);
            }
        });

        btnRegistarVeiculos.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistarVeiculos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegistarVeiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistarVeiculos.setText("<html> Registar <br> Manutenção</html>");
        btnRegistarVeiculos.setToolTipText("");
        btnRegistarVeiculos.setActionCommand("<html>Registar<br>Manutenção</html>");
        btnRegistarVeiculos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnRegistarVeiculos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistarVeiculos.setMinimumSize(new java.awt.Dimension(184, 62));
        btnRegistarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarManutencaoActionPerformed(evt);
            }
        });

        btnRegistarVeiculos2.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistarVeiculos2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegistarVeiculos2.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistarVeiculos2.setText("<html> Dar Início a <br> Preparação de Veículo</html>\n");
        btnRegistarVeiculos2.setToolTipText("");
        btnRegistarVeiculos2.setActionCommand("<html>Dar Início a<br>Preparação de Veículo</html>\n");
        btnRegistarVeiculos2.setMinimumSize(new java.awt.Dimension(184, 62));
        btnRegistarVeiculos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarPreparacaoActionPerformed(evt);
            }
        });

        btnRegistarVeiculos3.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistarVeiculos3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegistarVeiculos3.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistarVeiculos3.setText("<html>Visualizar Histórico <br> de Manutenções</html>\n");
        btnRegistarVeiculos3.setToolTipText("");
        btnRegistarVeiculos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisulizarManutencoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistarVeiculos2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistarVeiculos3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addComponent(btnVoltarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRegistarVeiculos2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistarVeiculos3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(btnRegistarVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarManutencaoActionPerformed
        RegistarManutencao janela = new RegistarManutencao();
        janela.setVisible(true);
    }//GEN-LAST:event_btnRegistarManutencaoActionPerformed

    private void btnVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenuActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnVoltarMenuActionPerformed

    private void btnRegistarPreparacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarPreparacaoActionPerformed
        RegistarPreparacao janela = new RegistarPreparacao();
        janela.setVisible(true);
    }//GEN-LAST:event_btnRegistarPreparacaoActionPerformed

    private void btnVisulizarManutencoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisulizarManutencoesActionPerformed
        VisualizarManutencoes janela = new VisualizarManutencoes();
        janela.setVisible(true);
    }//GEN-LAST:event_btnVisulizarManutencoesActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistarVeiculos;
    private javax.swing.JButton btnRegistarVeiculos2;
    private javax.swing.JButton btnRegistarVeiculos3;
    private javax.swing.JButton btnVoltarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
