package main.java.AutoSell;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import AutoSell.Clientes.Cliente;
import AutoSell.DadosAplicacao;
import AutoSell.Filiais.Filial;
import AutoSell.Pecas.Peca;
import AutoSell.Veiculos.Veiculo;
import main.java.AutoSell.Clientes.Menu_Clientes;
import main.java.AutoSell.Pecas.Menu_Pecas;
import main.java.AutoSell.Filiais.Menu_Filiais;
import AutoSell.Veiculos.Menu_Veiculos;
import main.java.AutoSell.Estatisticas.Menu_Estatisticas;
import AutoSell.Manutencoes.Menu_Manutencoes;
/**
 *
 * @author Tomas
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form AutoSell
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPecas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnVeiculos = new javax.swing.JButton();
        btnManutencoes = new javax.swing.JButton();
        btnTransacoes = new javax.swing.JButton();
        btnEventos = new javax.swing.JButton();
        btnFiliais = new javax.swing.JButton();
        btnEstatisticas = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(229, 229, 229));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));

        btnPecas.setBackground(new java.awt.Color(0, 0, 0));
        btnPecas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPecas.setForeground(new java.awt.Color(255, 255, 255));
        btnPecas.setText("Peças");
        btnPecas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPecas.setName("btn_pecas"); // NOI18N
        btnPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPecasActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(0, 0, 0));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Clientes");
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setName("btn_clientes"); // NOI18N
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnVeiculos.setBackground(new java.awt.Color(0, 0, 0));
        btnVeiculos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVeiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnVeiculos.setText("Veiculos");
        btnVeiculos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVeiculos.setName("btn_veiculos"); // NOI18N
        btnVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeiculosActionPerformed(evt);
            }
        });

        btnManutencoes.setBackground(new java.awt.Color(0, 0, 0));
        btnManutencoes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnManutencoes.setForeground(new java.awt.Color(255, 255, 255));
        btnManutencoes.setText("Manutenção");
        btnManutencoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManutencoes.setName("btn_manutencao"); // NOI18N
        btnManutencoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManutencaoActionPerformed(evt);
            }
        });

        btnTransacoes.setBackground(new java.awt.Color(0, 0, 0));
        btnTransacoes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnTransacoes.setForeground(new java.awt.Color(255, 255, 255));
        btnTransacoes.setText("Transações");
        btnTransacoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransacoes.setName("btn_transacoes"); // NOI18N
        btnTransacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransacoesActionPerformed(evt);
            }
        });

        btnEventos.setBackground(new java.awt.Color(0, 0, 0));
        btnEventos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEventos.setForeground(new java.awt.Color(255, 255, 255));
        btnEventos.setText("Eventos");
        btnEventos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEventos.setName("btn_eventos"); // NOI18N
        btnEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosActionPerformed(evt);
            }
        });

        btnFiliais.setBackground(new java.awt.Color(0, 0, 0));
        btnFiliais.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFiliais.setForeground(new java.awt.Color(255, 255, 255));
        btnFiliais.setText("Filiais");
        btnFiliais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFiliais.setName("btn_filiais"); // NOI18N
        btnFiliais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiliaisActionPerformed(evt);
            }
        });

        btnEstatisticas.setBackground(new java.awt.Color(0, 0, 0));
        btnEstatisticas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEstatisticas.setForeground(new java.awt.Color(255, 255, 255));
        btnEstatisticas.setText("Estatísticas");
        btnEstatisticas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstatisticas.setName("btn_estatisticas"); // NOI18N
        btnEstatisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatisticasActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setInheritsPopupMenu(true);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnManutencoes, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEstatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnTransacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnFiliais, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPecas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVeiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiliais, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManutencoes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEstatisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatisticasActionPerformed
        Menu_Estatisticas janela = new Menu_Estatisticas();
        janela.setVisible(true);
    }//GEN-LAST:event_btnEstatisticasActionPerformed

    private void btnFiliaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiliaisActionPerformed
        Menu_Filiais janela = new Menu_Filiais();
        janela.setVisible(true);
    }//GEN-LAST:event_btnFiliaisActionPerformed

    private void btnEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEventosActionPerformed

    private void btnTransacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransacoesActionPerformed

    private void btnManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManutencaoActionPerformed
        Menu_Manutencoes janela = new Menu_Manutencoes();
        janela.setVisible(true);
    }//GEN-LAST:event_btnManutencaoActionPerformed

    private void btnVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeiculosActionPerformed
        Menu_Veiculos janela =  new Menu_Veiculos();
        janela.setVisible(true);
    }//GEN-LAST:event_btnVeiculosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        Menu_Clientes janela =  new Menu_Clientes();
        janela.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPecasActionPerformed
        Menu_Pecas janela = new Menu_Pecas();
        janela.setVisible(true);
    }//GEN-LAST:event_btnPecasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        Cliente cliente1 = new Cliente("Tomás Neves","9669999999","2201747@my.ipleiria.pt","9999999990","R.Louriçal","3105-170 Louriçal");
        Cliente cliente2 = new Cliente("David Marques","9669555555","2201748@my.ipleiria.pt","153757701","R.Matas","3050-200 Matas");
        Cliente cliente3 = new Cliente("Rodrigo Domingues","966966666","2191173@my.ipleiria.pt","259376566","R.Leiria","3100-100 Leiria");
        Cliente cliente4 = new Cliente("Toze Menuel","966343456","email@gmail.com","280043910","R.Comibra","2500-200 Coimbra");
        Cliente cliente5 = new Cliente("Henrique Ferreira","966243267","teste@gemial.com","276517962","R.Lisboa","4100-150 Lisboa");


        Filial filial1 = new Filial("Auto Pombal","964444444","autoPombal@gmail.com","R.Pombal","3400-140 Pombal","Manuel António");
        Filial filial2 = new Filial("Auto Figueira","967575758","autoFigueira@gmail.com","R.Figueira","3759-042 Figueira","José Manuel");
        Filial filial3 = new Filial("Auto Leiria","965050504","autoLeiria@gmail.com","R.Leiria","2400-213 Leiria","Gabriel Ferreira");
        Filial filial4 = new Filial("Auto Algarve","961234567","autoAlgarve@gmail.com","R.Algarve","3008-430 Algarve","João Fernandes");
        Filial filial5 = new Filial("Auto Viseu","912345678","autoViseu@gmail.com","R.Viseu","2500-115 Viseu","Tiago Alexandre");

        Veiculo veiculo1 = new Veiculo("10-ZE-20","Golf","Volkswagen","José Manuel",2,"Gasóleo",false,"");
        Veiculo veiculo2 = new Veiculo("25-XX-10","Caddy","Volkswagen","José António",1,"Gasolina",false,"");
        Veiculo veiculo3 = new Veiculo("00-AA-00","Ibiza","Seat","Manuel António",5,"Gasóleo",true,"");
        Veiculo veiculo4 = new Veiculo("50-ZE-99","Clio","Renault","João Pedro",3,"Gasolina",false,"");
        Veiculo veiculo5 = new Veiculo("60-ZA-42","80","Audi","Tiago Manuel",3,"Gasóleo",false,"");

        Peca peca1 = new Peca("Volante","123456789","Bosch",2,"Sede",veiculo1.marca+"/"+veiculo1.modelo);
        Peca peca2 = new Peca("Acelarador","111111111","3M",6,filial1.nome,veiculo2.marca+"/"+veiculo2.modelo);
        Peca peca3 = new Peca("Colunas ","112222222","JVC",10,filial2.nome,veiculo3.marca+"/"+veiculo3.modelo);
        Peca peca4 = new Peca("Puxador ","232521597","Renault",5,"Sede",veiculo4.marca+"/"+veiculo4.modelo);
        Peca peca5 = new Peca("Jante ","847569697","BBS",4,filial5.nome,veiculo5.marca+"/"+veiculo5.modelo);


        DadosAplicacao.INSTANCE.adicionarCliente(cliente1);
        DadosAplicacao.INSTANCE.adicionarCliente(cliente2);
        DadosAplicacao.INSTANCE.adicionarCliente(cliente3);
        DadosAplicacao.INSTANCE.adicionarCliente(cliente4);
        DadosAplicacao.INSTANCE.adicionarCliente(cliente5);

        DadosAplicacao.INSTANCE.adicionarFilial(filial1);
        DadosAplicacao.INSTANCE.adicionarFilial(filial2);
        DadosAplicacao.INSTANCE.adicionarFilial(filial3);
        DadosAplicacao.INSTANCE.adicionarFilial(filial4);
        DadosAplicacao.INSTANCE.adicionarFilial(filial5);

        DadosAplicacao.INSTANCE.adicionarVeiculo(veiculo1);
        DadosAplicacao.INSTANCE.adicionarVeiculo(veiculo2);
        DadosAplicacao.INSTANCE.adicionarVeiculo(veiculo3);
        DadosAplicacao.INSTANCE.adicionarVeiculo(veiculo4);
        DadosAplicacao.INSTANCE.adicionarVeiculo(veiculo5);

        DadosAplicacao.INSTANCE.adicionarPeca(peca1);
        DadosAplicacao.INSTANCE.adicionarPeca(peca2);
        DadosAplicacao.INSTANCE.adicionarPeca(peca3);
        DadosAplicacao.INSTANCE.adicionarPeca(peca4);
        DadosAplicacao.INSTANCE.adicionarPeca(peca5);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEstatisticas;
    private javax.swing.JButton btnEventos;
    private javax.swing.JButton btnFiliais;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManutencoes;
    private javax.swing.JButton btnPecas;
    private javax.swing.JButton btnTransacoes;
    private javax.swing.JButton btnVeiculos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
