/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.AutoSell.Estatisticas;

/**
 *
 * @author David
 */


import main.java.AutoSell.Veiculos.*;
import main.java.AutoSell.Clientes.*;
import main.java.AutoSell.Clientes.VisualizarClientes;
import main.java.AutoSell.Estatisticas.EstatisticasMarca;
import main.java.AutoSell.Estatisticas.EstatisticasFiliais;
import main.java.AutoSell.Estatisticas.EstatisticasFeiras;
import main.java.AutoSell.Estatisticas.EstatisticasClientes;
public class Menu_Estatisticas extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Clientes
     */
    public Menu_Estatisticas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltarMenu = new javax.swing.JButton();
        btnEstatisticasMarca = new javax.swing.JButton();
        btnEstatisticasClientes = new javax.swing.JButton();
        btnEstatisticasFiliais = new javax.swing.JButton();
        btnEstatisticasFeiras = new javax.swing.JButton();

        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestão Estatísticas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        btnVoltarMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnVoltarMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVoltarMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarMenu.setText("Voltar ao Menu Principal");
        btnVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenuActionPerformed(evt);
            }
        });

        btnEstatisticasMarca.setBackground(new java.awt.Color(0, 0, 0));
        btnEstatisticasMarca.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEstatisticasMarca.setForeground(new java.awt.Color(255, 255, 255));
        btnEstatisticasMarca.setText("<html>Marcas<br>mais<br>vendidas</html>");
        btnEstatisticasMarca.setToolTipText("");
        btnEstatisticasMarca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstatisticasMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatisticaMarcaActionPerformed(evt);
            }
        });

        btnEstatisticasClientes.setBackground(new java.awt.Color(0, 0, 0));
        btnEstatisticasClientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEstatisticasClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnEstatisticasClientes.setText("Clientes");
        btnEstatisticasClientes.setToolTipText("");
        btnEstatisticasClientes.setMaximumSize(new java.awt.Dimension(2147483647, 90));
        btnEstatisticasClientes.setMinimumSize(new java.awt.Dimension(134, 90));
        btnEstatisticasClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatisticasClientesActionPerformed(evt);
            }
        });

        btnEstatisticasFiliais.setBackground(new java.awt.Color(0, 0, 0));
        btnEstatisticasFiliais.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEstatisticasFiliais.setForeground(new java.awt.Color(255, 255, 255));
        btnEstatisticasFiliais.setText("<html>Melhores<br>Filiais</html>");
        btnEstatisticasFiliais.setToolTipText("");
        btnEstatisticasFiliais.setMaximumSize(new java.awt.Dimension(2147483647, 90));
        btnEstatisticasFiliais.setMinimumSize(new java.awt.Dimension(134, 90));
        btnEstatisticasFiliais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatisticasFiliaisActionPerformed(evt);
            }
        });

        btnEstatisticasFeiras.setBackground(new java.awt.Color(0, 0, 0));
        btnEstatisticasFeiras.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEstatisticasFeiras.setForeground(new java.awt.Color(255, 255, 255));
        btnEstatisticasFeiras.setText("<html>Melhores<br>Feiras</html>");
        btnEstatisticasFeiras.setToolTipText("");
        btnEstatisticasFeiras.setMaximumSize(new java.awt.Dimension(2147483647, 90));
        btnEstatisticasFeiras.setMinimumSize(new java.awt.Dimension(134, 90));
        btnEstatisticasFeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatisticasFeirasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnEstatisticasMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEstatisticasClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEstatisticasFiliais, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEstatisticasFeiras, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstatisticasMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(btnEstatisticasClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstatisticasFiliais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstatisticasFeiras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(btnVoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstatisticaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatisticaMarcaActionPerformed
        EstatisticasMarca janela = new EstatisticasMarca();
        janela.setVisible(true);
    }//GEN-LAST:event_btnEstatisticaMarcaActionPerformed

    private void btnEstatisticasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatisticasClientesActionPerformed
        EstatisticasClientes janela = new EstatisticasClientes();
        janela.setVisible(true);
    }//GEN-LAST:event_btnEstatisticasClientesActionPerformed

    private void btnEstatisticasFiliaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatisticasFiliaisActionPerformed
        EstatisticasFiliais janela = new EstatisticasFiliais();
        janela.setVisible(true);
    }//GEN-LAST:event_btnEstatisticasFiliaisActionPerformed

    private void btnEstatisticasFeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatisticasFeirasActionPerformed
        EstatisticasFeiras janela = new EstatisticasFeiras();
        janela.setVisible(true);
    }//GEN-LAST:event_btnEstatisticasFeirasActionPerformed

    private void btnVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenuActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnVoltarMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstatisticasClientes;
    private javax.swing.JButton btnEstatisticasFeiras;
    private javax.swing.JButton btnEstatisticasFiliais;
    private javax.swing.JButton btnEstatisticasMarca;
    private javax.swing.JButton btnVoltarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
